#!/bin/sh

BASEDIR=$(dirname "$0")

$BASEDIR/node_modules/.bin/electron $BASEDIR/main.js $@

# TEMPFILE="/tmp/md-preview"
# HTMLFILE="/tmp/md-preview.html"
# TEMPLATEFILE="template.erb"

# markdown $1 > $TEMPFILE
# MD_PREVIEW_FILE=$TEMPFILE erb $TEMPLATEFILE > $HTMLFILE
# xdg-open $HTMLFILE
